# Generated by Django 5.1 on 2024-09-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadechatai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='product_image',
            field=models.URLField(blank=True),
        ),
    ]
