# Generated by Django 5.1 on 2024-09-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadechatai', '0002_chat_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='product_image',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
