# Generated by Django 5.1 on 2024-09-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadechatai', '0003_remove_chat_product_image_chat_chat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='zadechatai/chat/'),
        ),
    ]
