# Generated by Django 5.1 on 2024-09-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadechatai', '0004_alter_chat_chat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chat_image',
            field=models.ImageField(blank=True, null=True, upload_to='zadechatai/chat/'),
        ),
    ]
