# Generated by Django 5.1 on 2024-09-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zadechatai', '0007_alter_chat_chat_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='chat_image',
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_url',
            field=models.CharField(default='', max_length=500),
        ),
    ]
